source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "logger", "~> 1.7.0"
gem "colorize", "~> 1.1.0"
gem "rake", "~> 13.3.0"
gem "erb", "~> 5.0.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jektify", path: "/home/boss/Projects/github/jektify"
end