source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "logger", "~> 1.7.0"
gem "csv", "~> 3.3.2"
gem "colorize", "~> 1.1.0"
gem "rake", "~> 13.3.0"
gem "sass", "~> 3.7.4"
gem "erb", "~> 5.0.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end